#!/usr/bin/env python3

from sys import argv, exit, stderr
from CacheManager import CacheManager

def main():
    """
    Purpose: Program entry point; this program utilizes the CacheManager.buildPartialDiskCache() static method,
        which creates a /cache/ folder containing 13 MB of compressed article content (in particular, this
        /cache/ folder contains articles of rank 215 through 357 according to pageviews.csv - see CacheManager.py 
        for more information).
    :return: Void.
    """
    arg_vector = argv
    if len(arg_vector) != 1:  # should be "./built_partial_disk_cache"
        print("Arguments should be of the form: \"./build_partial_disk_cache\"", file=stderr)
        print("Exiting...", file=stderr)
        exit(1)
    CacheManager.buildPartialDiskCache("cs5700cdnorigin.ccs.neu.edu", 
            "8080",
            "pageviews.csv"
    )

if __name__ == "__main__":
    main()

